name: Bug Report
description: Report a bug or issue with the AI Code Reviewer package
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug in the AI Code Reviewer package. Please fill out the information below to help us diagnose and fix the issue.
        
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please ensure you've completed these steps before submitting an issue
      options:
        - label: I have verified this is not a duplicate issue by searching existing issues
          required: true
        - label: I have updated to the latest version of the package
          required: true
        - label: I have read the documentation and confirmed this is a bug
          required: true
          
  - type: input
    id: laravel_version
    attributes:
      label: Laravel Version
      description: What version of Laravel are you using?
      placeholder: e.g., 11.0.0
    validations:
      required: true
      
  - type: input
    id: php_version
    attributes:
      label: PHP Version
      description: What version of PHP are you using?
      placeholder: e.g., 8.2.0
    validations:
      required: true
      
  - type: input
    id: package_version
    attributes:
      label: Package Version
      description: What version of AI Code Reviewer are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: When I try to do X, Y happens instead of Z
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure the package with ...
        2. Set up a webhook to ...
        3. Create a pull request ...
        4. See error ...
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: If applicable, add logs or error messages
      render: shell
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be relevant 